name = "labex-course-cover"
main = "src/index.ts"
compatibility_date = "2025-02-04"
workers_dev = true
preview_urls = true

[[routes]]
pattern = "cover-creator.labex.io"
zone_name = "labex.io"
custom_domain = true

[observability]
enabled = false

[observability.logs]
enabled = true
head_sampling_rate = 0.1
invocation_logs = true

[[kv_namespaces]]
id = "ef1d0658912e4bb7a4d3809fa4435df2"
binding = "COURSE_COVER_KV"
